### ISSUE TITLE
Cubic panorama does not display front image

### ISSUE THREAD

**Issue by CodeCombiner** [niveuseverto/panoramagl-android#30]
Hi, add images for panorama and it does not display front image only. Sometimes it displays front image, but almost always it does not.

**Comment by niveuseverto** [comment]
Sorry, I missed this issue, will try to test and find out what is going wrong

**Comment by CodeCombiner** [comment]
I update the project , recompiled and now it works

**Comment by niveuseverto** [comment]
Pull request will be appreciated if applicable

**Comment by CodeCombiner** [comment]
I just remember that I was using gradle implementation of this project, https://github.com/marianmoldovan/panoramagl

**Comment by niveuseverto** [comment]
Thanks you for pointing out, will check that repo!
